title: "Morphic"
logo: "/assets/main/Logo_EBI_1.png"
site_url: https://morphic-bio.github.io/
remote_theme: just-the-docs/just-the-docs
search:
  heading_level: 2
  previews: 5
  # Enable hyphenated words
  tokenizer_separator: /[\s/]+/
search_enabled: true

mermaid:
  version: "9.1.7"


aux_links:
  "About MorPHiC":
    - "aux/about.html"
  "Edit these Docs on GitHub":
    - "https://github.com/morphic-bio/homepage"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

markdown: kramdown

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/morphic-bio/homepage" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: "./" # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
