import React from 'react';
import Feature from '../../components/feature/Feature';
import './whatmorphic.css';

const Whatmorphic = () => (
  <section className="morphic__whatmorphic section__margin" id="wmorphic">
    <div className="morphic__whatmorphic-heading">
      <h1 className="gradient__text">What is MorPhiC</h1>
    </div>
    <p className="morphic__features-paragraph">The MorPhiC programme aims to develop a consistent catalog of molecular and cellular phenotypes for null alleles for every human gene by using in-vitro multicellular systems. The catalog will be made available for broad use by the biomedical community. </p>
    <p className="morphic__features-paragraph">MorPhiC has three components: the Data Production Research and Development Centers (DPCs), the Data Analysis and Validation Centers (DAVs) and the Data Resource and Administrative Coordinating Center (DRACC).</p>
    <div className="morphic__whatmorphic-container">
      <Feature title="DPCs" text="Develop diverse systems and assays and explore and compare approaches to produce MorPhiC data at scale." id="DPC" />
      <Feature title="DAVs" text="Analyse the data generated by DPCs to characterize its quality and utility for multiple purposes" id="DAV" />
      <Feature title="DRACC" text="Coordinate the data to ensure FAIRness, storage and distribution" id="DRACC" />
    </div>
  </section>
);

export default Whatmorphic;
